### ISSUE TITLE
Webpack is wrongly setting rootDirectoryLevel to 2

### ISSUE THREAD

**Issue by lopes-gustavo** [joeldenning/systemjs-webpack-interop#21]
I'm using this line `config.plugins.push(new SystemJSPublicPathWebpackPlugin({ systemjsModuleName: '@my-org/my-module' }))` in my Vue application.

It has a few of other plugins installed (fyi `quasar` and `single-spa`).

What is weird is that `resource_query_public_path` is setting `queryObj.rootDirectoryLevel` to 2, regardless of I setting it to 1. 

I'm trying to debug it, but I get to the global `__resourceQuery`, which I cannot understand where it comes from (the wrong value is there).

Can anyone help me find who is messing with the `rootDirectoryLevel` property? 
Thanks

**Comment by joeldenning** [comment]
Hi @lopes-gustavo, here's the line of code you're looking for:

https://github.com/single-spa/vue-cli-plugin-single-spa/blob/89d9868f1b3ff9db1870452e23586cd78f89e503/index.js#L34

We set the root directory level to 2 because Vue CLI projects have the following directory structure in their output:

```sh
dist/
  js/
    app.js
  css/
    main.css
```

The public path for Vue CLI projects should point to the `dist` directory, instead of `dist/js`, which is why the root directory level is 2.

If that output directory structure doesn't match what Quasar produces, then you should modify the rootDirectoryLevel in the webpack config:

```js
// In vue.config.js
module.exports = {
  chainWebpack(config) {
    config.plugin('SystemJSPublicPathWebpackPlugin').tap((args) => {
      args[0].rootDirectoryLevel = 1;
      return args
    })
  }
}

// Or if Quasar uses just a webpack config:
const config = getFromQuasarSomehow();
config.plugins.find(p => p.constructor.name === 'SystemJSPublicPathWebpackPlugin').rootDirectoryLevel = 1
```

This has come up once before, too, so I think I'll add some documentation for it.

**Comment by lopes-gustavo** [comment]
Perfect!!
I tried to force it with `config.plugins.push(new SystemJSPublicPathWebpackPlugin({ systemjsModuleName: '@my-org/my-module', rootDirectoryLevel: 1 }))`, but it was overridden somewhere I couldn't find out where.
I didn't know about that `tap` method.
Thanks

**Comment by joeldenning** [comment]
For reference, here's the PR to update the docuemntation: https://github.com/single-spa/single-spa.js.org/pull/397
